### ISSUE TITLE
Laskin - Määrämuunnin

### ISSUE THREAD

**Issue by Timppari** [dogiex/MIUI-XML-12-FINNISH#2]
**Kuvaile käännösvirhe**
Laskimen muuntimessa käännetty "Äänenvoimakkuus".

**Mistä käännösvirheen löytää**
Askeleet:
1. Siirry 'Mi Laskin'

**Odotettu käännös**
Äänenvoimakkuus  --> Määrämuunnin, parempi olisi "**Tilavuus**" 

**Kuvakaappaus**
![Screenshot_2020-12-10-18-16-44-493_com miui calculator](https://user-images.githubusercontent.com/57177848/101799734-2ec5d080-3b15-11eb-898d-5c66cd71d2da.jpg)
![Screenshot_2020-12-10-18-16-55-160_com miui calculator](https://user-images.githubusercontent.com/57177848/101799739-2ff6fd80-3b15-11eb-818d-9813e278d6d4.jpg)

**Älypuhelin (täytä alla olevat tiedot):**
 - Laite: [Mi10T Pro 5G]
 - MIUI-versio: [esim. 12.0.10]

**Lisäsisältö**

**Comment by dogiex** [comment]
Käytätkö varmasti Xiaomi.eu custom rommia vai onko käytössäsi virallinen MIUI?
Jos käytössäsi on virallinen MIUI-käyttöjärjestelmä, tee vikailmoitus palautesovelluksen kautta.
Xiaomi.eu custom rommissa ei ole ilmoittamaasi ongelmaa.

**Comment by Timppari** [comment]
Hei,
Tosiaankin tämä on virallinen MIUI, jossa virhe.

su 13. jouluk. 2020 klo 21.17 Dogiex <notifications@github.com> kirjoitti:
